[package]
name = "libfuzzer-sys"
version = "0.1.1"
authors = ["The cargo-fuzz Project Developers"]
repository = "https://github.com/rust-fuzz/libfuzzer-sys"
license = "MIT/Apache-2.0/NCSA"
description = "LibFuzzer wrapper for Rust"

# cargo-fuzz puts this in a crate subdirectory,
# which causes problems if the crate uses workspaces.
# Create a useless local workspace to break out of this
[workspace]
members = ["."]

[dependencies]
arbitrary = "0.1"

[build-dependencies]
cc = "1.0"
